---
apiVersion: v1
kind: Secret
metadata:
  name: argocd-helm-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://argoproj.github.io/argo-helm
  name: argo
  type: helm
---
apiVersion: v1
kind: Secret
metadata:
  name: sigstore-helm-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://sigstore.github.io/helm-charts
  name: sigstore
  type: helm
