project_id         = "REPLACE ME"
region             = "asia-south1"
cluster_name       = "gitops-kickstarter"
kubernetes_version = "1.23."
release_channel    = "stable"
gitops_repo        = "https://github.com/harness-apps/gitops-quickstart.git"